name: build and publish

on:
  push:
    branches:
      - trunk
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: |
            jakewharton/gphotos-sync
            ghcr.io/jakewharton/gphotos-sync
          tag-semver: |
            {{version}}
            {{major}}
            {{major}}.{{minor}}

      - uses: docker/login-action@v1.10.0
        with:
          username: jakewharton
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v1

      # See https://gitlab.alpinelinux.org/alpine/aports/-/issues/12406
      - run: docker run --rm --privileged linuxkit/binfmt:v0.8

      - uses: docker/build-push-action@v2.7.0
        with:
          build-args: --progress plain
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
